export const routes = {
  GEN_WALLET: 'GET_WALLET',
  CONFIRM_WALLET: 'CONFIRM_WALLET',
  ONBOARDING: 'ONBOARDING',
  CREATE_WALLET: 'CREATE_WALLET',
  IMPORT_WALLET: 'IMPORT_WALLET',
  HOME: 'home',
  LOGIN: 'login',
  REGISTER: 'register',
  TWA: 'twa',
  BOTTOM_TAB: 'bottom_tab',
  SEND: 'send',
  RECEIVE: 'receive',
  BUY: 'buy',
  SELL: 'sell',
  NOTIFICATIONS: 'notifications',
  HISTORY: 'History',
  ADD_TOKEN: 'add token',
  TOKEN_DETAILS: 'token_details',
  SETTING: 'settings',
  PROFILE: 'profile',
  MARKET: 'market',
  SWAP: 'swap'
};
